import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import '../../../../core/domain/utils_and_services/helpers.dart';

part 'todo_model_immutable.freezed.dart';

/// 📝 Immutable model for Todo item (Freezed-based)
@freezed
class Todo with _$Todo {
  /// Main constructor
  const factory Todo({
    required String id,
    required String description,
    @Default(false) bool completed,
  }) = _Todo;

  /// Factory for creating a new Todo with autogenerated id
  factory Todo.add({required String description}) {
    return Todo(id: uuid.v4(), description: description);
  }
}
