import '../../../../core/domain/utils_and_services/helpers.dart';

/// 📝 Mutable model for Todo item
class Todo {
  String id;
  String description;
  bool completed;

  /// Standard constructor
  Todo({required this.id, required this.description, this.completed = false});

  /// Factory for creating a new Todo with autogenerated id
  factory Todo.add({required String description}) {
    return Todo(id: uuid.v4(), description: description);
  }

  @override
  String toString() =>
      'Todo(id: $id, description: $description, completed: $completed)';
}
