import '../../../../core/domain/utils_and_services/helpers.dart';

/// 📝 Mutable model for Todo item
class MutableTodoModel {
  String id;
  String description;
  bool completed;

  /// Standard constructor
  MutableTodoModel({
    required this.id,
    required this.description,
    this.completed = false,
  });

  /// Factory for creating a new Todo with autogenerated id
  factory MutableTodoModel.add({required String description}) {
    return MutableTodoModel(id: uuid.v4(), description: description);
  }

  @override
  String toString() =>
      'Todo(id: $id, description: $description, completed: $completed)';
}
